# Generated by Django 5.0 on 2023-12-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_app', '0003_alter_vehicle_vehicle_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
